#!/usr/bin/env python3
"""generate-dir-readme.py — 任意の dir の README.md を、 各 file 冒頭の説明 1 行目から生成する (README に正本を置かないための索引生成器)

使い方:
  generate-dir-readme.py --dir <dir> --title <見出し> [--note <前置き>] [--describe NAME=説明 ...] [--cmd <再生成の command>] --write
  generate-dir-readme.py --dir <dir> ... --check      # 再生成せず比較、 drift があれば exit 1 (説明の欠けは exit 2)
  generate-dir-readme.py --selftest

なぜ要るか: 手書きの README に script の詳細を書くと、 README が正本になって script 本体と二重に持つ
(= どちらかが古くなる)。 README は索引に徹し、 詳細は各 file 冒頭 (docstring / 先頭の注釈) に置く。
本 script は README を file 冒頭から生成し、 --check で手編集と説明の書き忘れを止める
(規約 = conventions/memory-file-slimming.md#generated-block-slimming の「README に正本を置かない」)。

説明の源 = scripts/generate-tree.py の extract_header_desc (compile して読む = 同じ規則):
  .py = module docstring 1 行目 / .sh .txt .yaml 等 = shebang 直後の最初の # 注釈 / .js 等 = // 注釈 /
  .json = top-level "_comment" の最初の文。 いずれも先頭の "<名前> — " は外す。
  注釈を持てない file (機械が書く .json 等) は --describe NAME=説明 で渡す。
  subdir は、 その中の README.md の最初の見出し以外の行か --describe で説明する。

stdlib only / 公開層 (個人の値を持たない。 dir・見出し・前置き・説明の上書きは呼び出し側が渡す)。
"""
from __future__ import annotations

import argparse
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
MARK = "<!-- AUTO-GENERATED by generate-dir-readme.py — 手編集禁止。"


def _load_extractor():
    ns = {"__name__": "generate_tree_for_dir_readme", "__file__": str(HERE / "generate-tree.py")}
    src = (HERE / "generate-tree.py").read_text(encoding="utf-8")
    exec(compile(src, str(HERE / "generate-tree.py"), "exec"), ns)
    return ns["extract_header_desc"]


def _dir_desc(p: Path):
    readme = p / "README.md"
    if not readme.exists():
        return None
    for line in readme.read_text(encoding="utf-8", errors="replace").splitlines():
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith("<!--"):
            return s
    return None


def _tracked_names(d: Path):
    """git が追跡している (index に在る) d 直下の名前の集合。 git repo でなければ None (= 全部を源にする)。
    手元だけの一時 file や ignore された生成物を源にすると、 マシンごとに README が変わるため。"""
    import subprocess
    try:
        r = subprocess.run(["git", "-C", str(d), "ls-files", "-z", "--", "."],
                           capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.SubprocessError):
        return None
    if r.returncode != 0:
        return None
    return {x.split("/", 1)[0] for x in r.stdout.split("\0") if x}


def render(d: Path, title: str, note: str, describe: dict, cmd: str, extract=None, tracked="auto"):
    extract = extract or _load_extractor()
    if tracked == "auto":
        tracked = _tracked_names(d)
    rows, dirs, missing = [], [], []
    for p in sorted(d.iterdir(), key=lambda x: x.name.lower()):
        n = p.name
        if n.startswith(".") or n == "__pycache__" or n.endswith(".pyc") or n == "README.md":
            continue
        if tracked is not None and n not in tracked:
            continue
        if p.is_dir():
            desc = describe.get(n) or describe.get(n + "/") or _dir_desc(p)
            if not desc:
                missing.append(n + "/")
            dirs.append((n + "/", desc or ""))
            continue
        desc = describe.get(n) or extract(p)
        if not desc:
            missing.append(n)
        rows.append((n, desc or ""))
    lines = [
        MARK,
        "     源 = 各 file 冒頭の説明 1 行目 (.py = docstring / それ以外 = 先頭の注釈)。 詳細は各 file 冒頭が正本。",
        f"     再生成: {cmd} --write / 同期検査: --check -->",
        "",
        f"# {title}",
        "",
    ]
    if note:
        lines += [note, ""]
    for n, desc in rows:
        lines.append(f"- **[{n}]({n})** — {desc}")
    if dirs:
        lines += ["", "## directories", ""]
        for n, desc in dirs:
            lines.append(f"- **[{n}]({n})** — {desc}")
    return "\n".join(lines).rstrip() + "\n", missing


def selftest() -> int:
    ok = True

    def check(cond, label):
        nonlocal ok
        print(("PASS " if cond else "FAIL ") + label)
        ok = ok and cond

    with tempfile.TemporaryDirectory() as t:
        d = Path(t)
        (d / "b.py").write_text('"""b.py — second tool\n\ndetails not in index\n"""\n# 運用メモ\n', encoding="utf-8")
        (d / "a.sh").write_text("#!/bin/sh\n# a.sh — first tool\n# more\n", encoding="utf-8")
        (d / "state.json").write_text('{"x": 1}\n', encoding="utf-8")
        (d / "sub").mkdir()
        (d / "sub" / "README.md").write_text("# sub\n\nsub の説明\n", encoding="utf-8")
        (d / "README.md").write_text("hand written\n", encoding="utf-8")
        out, missing = render(d, "T", "note", {}, "gen")
        check(out.index("a.sh") < out.index("b.py"), "名前順")
        check("— first tool" in out and "— second tool" in out, "名前 prefix を外した説明 1 行目")
        check("details not in index" not in out and "運用メモ" not in out, "2 行目以降と docstring 後の注釈は索引に出ない")
        check(missing == ["state.json"], "注釈を持てない json は説明の欠けとして出る")
        check("hand written" not in out, "既存 README は源にしない")
        check("sub の説明" in out, "subdir は中の README の本文 1 行目")
        out2, missing2 = render(d, "T", "", {"state.json": "機械が書く状態"}, "gen")
        check(missing2 == [] and "— 機械が書く状態" in out2, "--describe で欠けを埋める")
        check(out2.startswith(MARK), "生成物の印")
        out3, _ = render(d, "T", "", {"state.json": "x"}, "gen", tracked={"b.py", "sub"})
        check("a.sh" not in out3 and "b.py" in out3, "git が追跡していない file は源にしない")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dir")
    ap.add_argument("--title", default="")
    ap.add_argument("--note", default="")
    ap.add_argument("--describe", action="append", default=[], help="NAME=説明 (注釈を持てない file / dir)")
    ap.add_argument("--cmd", default="python3 generate-dir-readme.py --dir <dir> ...", help="README に書く再生成の command")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if not a.dir or not a.title:
        ap.error("--dir と --title が要る")
    d = Path(a.dir).expanduser().resolve()
    describe = {}
    for kv in a.describe:
        k, _, v = kv.partition("=")
        describe[k.strip()] = v.strip()
    out, missing = render(d, a.title, a.note, describe, a.cmd)
    if missing:
        print("説明 1 行目が無い file (冒頭に docstring / 注釈を書くか --describe で渡す): " + ", ".join(missing), file=sys.stderr)
        return 2
    target = d / "README.md"
    if a.write:
        target.write_text(out, encoding="utf-8")
        print(f"wrote {target}")
        return 0
    cur = target.read_text(encoding="utf-8") if target.exists() else ""
    if cur != out:
        print(f"{target} が生成物と一致しない (手編集か、 file 冒頭の説明の変更後に --write していない)", file=sys.stderr)
        return 1
    print(f"{target} is in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
